id: de.gematik.epa
canonical: https://gematik.de/fhir/epa
name: EPA_Basic
title: "ePA Basisfunktionalit채ten"
jurisdiction: "urn:iso:std:iso:3166#DE"

experimental: false
status: draft # draft | active | retired | unknown
version: 1.1.5
date: 2025-03-31

copyrightYear: 2025+
#Flip releaseLabel to 'release' for publication. Flip to 'ci-build' for CI
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

fhirVersion: 4.0.1

publisher:
  name: gematik GmbH
  url: https://www.gematik.de
  email: patientteam [ at ] gematik.de

dependencies:
  de.basisprofil.r4: 1.5.3
  de.gematik.terminology: 1.0.6
  de.gematik.ti: 1.1.0

# FSHOnly: true


pages:
  index.md:
    title: Home
  general-principles.md:
    title: "Generelle Prinzipien"
  privacy-security.md:
    title: "Datenschutz und Sicherheit"
  api-audit.md:
    title: "Basisdienst Audit Event Service"
    query-api-audit-event.md:
      title: "Audit Service: Query API"
    render-api-audit-event.md:
      title: "Audit Service: Render API"
  api-patient.md:
    title: "Basisdienst Patient Service"
    query-api-patient.md:
      title: "Patient Service: Query API"
    upsert-patient.md:
      title: "Patient Service: Versicherteninformationen hinzuf체gen/aktualisieren"
  artifacts.md:
    title: "FHIR-Artefakte"
  referenced.md:
    title: "Referenzen"
  downloads.md:
    title: "Downloads"
  release-notes.md:
    title: "Release Notes"
  spec-sheet.md:
    title: "Steckbriefe"
    actor-medication.md:
      title: "Steckbrief: ePA Medication Service"
    actor-audit.md:
      title: "Steckbrief: ePA Audit Event Service"
    actor-patient.md:
      title: "Steckbrief: ePA Patient Service"
    actor-mhd.md:
      title: "Steckbrief: ePA MHD Service"
    actor-client.md:
      title: "Steckbrief: ePA PS / ePA-Client-Systeme / ePA-FdV"


menu:
  Home: index.html
  Generelle Prinzipien:
    Generelle Prinzipien: general-principles.html
    Datenschutz und Sicherheit: privacy-security.html
  Audit Service:
    "Audit Service": api-audit.html
    "Audit Service: Query API": query-api-audit-event.html
    "Audit Service: Render API": render-api-audit-event.html
    "Alle Anforderungen": actor-audit.html
  Patient Service:
    "Patient Service": api-patient.html
    "Patient Service: Query API": query-api-patient.html
    "Patient Service: Hinzuf체gen/Aktualisieren": upsert-patient.html
    "Alle Anforderungen": actor-patient.html
  FHIR-Artefakte: artifacts.html
  Anh채nge:
    Referenzen: referenced.html
    Downloads: downloads.html
    Release Notes: release-notes.html
    Steckbriefe: spec-sheet.html


parameters:
  apply-publisher: false
  default-publisher: true
  apply-contact: false
  default-contact: true
  no-usage-check: true
  excludettl: true
  no-narrative:
    - StructureDefinition/*
    - AuditEvent/*
    - Bundle/*
    - Patient/*
    - OperationOutcome/*
  path-resource:
    - fsh-generated/resources
    - extracted/resources
  path-pages:
    - input/intro-notes


instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  # setId: always # always | standalone-only

### EPA TOOLS

merger:
  # path-resource: fsh-generated/resources
  path-resource: data
  base:
    packages: de.gematik.epa
    version: current
    resource: CapabilityStatement/epa-basic-server
  resource:
    - CapabilityStatement/epa-patient-server
    - CapabilityStatement/epa-medication-service-server
    - CapabilityStatement/epa-audit-event-server

openapi:
  path-output: output
  path-resource: data
  capability-statement:
    - input: CapabilityStatement/epa-patient-server
      output: epa-patient-server.openapi.json
      additional-openapi: openapis/manual-operations.yaml
    - input: CapabilityStatement/epa-patient-server
      output: epa-patient-server.openapi.yaml
      additional-openapi: openapis/manual-operations.yaml
    - input: CapabilityStatement/epa-medication-service-server
      output: epa-medication-service-server.openapi.json
      additional-openapi: openapis/manual-operations.yaml
    - input: CapabilityStatement/epa-medication-service-server
      output: epa-medication-service-server.openapi.yaml
      additional-openapi: openapis/manual-operations.yaml
    - input: CapabilityStatement/epa-audit-event-server
      output: epa-audit-event-server.openapi.json
      additional-openapi: openapis/manual-operations.yaml
    - input: CapabilityStatement/epa-audit-event-server
      output: epa-audit-event-server.openapi.yaml
      additional-openapi: openapis/manual-operations.yaml