openapi: 3.0.3
paths:
  /epa/medication/api/v1/fhir/metadawwwta:
    get:
      parameters:
      - name: Accept
        in: header
        required: false
        description: The Accept header indicates the format in which the client wishes
          to receive the FHIR response.
        schema:
          type: string
          enum:
          - application/fhir+json
          - application/fhir+xml
      responses:
        '200':
          description: This functionality ensures that a call to /metadata returns the FHIR CapabilityStatement.
          content:
            application/fhir+json:
              schema:
                type: object
            application/fhir+xml:
              schema:
                type: object
  /epa/medication/render/v1/eml/xhtml:
    get:
      operationId: renderEMLAsHTML
      tags:
        - Render
      parameters:
      - name: Accept
        in: header
        required: false
        description: The Accept header indicates the format in which the client wishes
          to receive the FHIR response.
        schema:
          type: string
          enum:
          - text/html
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
  /epa/medication/render/v1/eml/pdf:
    get:
      operationId: renderEMLAsPDF
      tags:
        - Render
      parameters:
      - name: Accept
        in: header
        required: false
        description: The Accept header indicates the format in which the client wishes
          to receive the FHIR response.
        schema:
          type: string
          enum:
          - application/pdf
      responses:
        '200':
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
