openapi: 3.0.3
paths:
  /epa/medication/api/v1/fhir/metadata:
    get:
      responses:
        '200':
          description: This functionality ensures that a call to /metadata returns the FHIR CapabilityStatement.
          content:
            application/fhir+json:
              schema:
                type: object
            application/fhir+xml:
              schema:
                type: object
  /epa/medication/render/v1/eml/xhtml:
    get:
      operationId: renderEMLAsHTML
      tags:
        - Render
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
  /epa/medication/render/v1/eml/pdf:
    get:
      operationId: renderEMLAsPDF
      tags:
        - Render
      responses:
        '200':
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
